server:
  port: 8080
#encrypt:
#  key-store:
#    alias:


security:
  oauth2:
    client: #http://localhost:8080/auth/oauth/authorize
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
      client-id: c1
      client-secret: sc1
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
      token-info-uri: http://localhost:8080/oauth/tokenInfo